#!/bin/bash
BASE_URL="https://nyem.gnosisbrand.com/backend/public/api"

echo "=== Testing Live API Routes ==="
echo ""

echo "1. Base endpoint:"
curl -s "$BASE_URL/" | jq . 2>/dev/null || curl -s "$BASE_URL/"
echo ""
echo ""

echo "2. Auth endpoints available:"
echo "   POST $BASE_URL/auth/send-otp"
echo "   POST $BASE_URL/auth/verify-otp"
echo "   POST $BASE_URL/auth/login"
echo "   POST $BASE_URL/auth/register"
echo ""

echo "3. Protected endpoints (require Bearer token):"
echo "   GET  $BASE_URL/profile/me"
echo "   PUT  $BASE_URL/profile/update"
echo "   PUT  $BASE_URL/profile/update-password"
echo "   POST $BASE_URL/items"
echo "   GET  $BASE_URL/items/feed"
echo "   GET  $BASE_URL/items/{id}"
echo "   PUT  $BASE_URL/items/{id}"
echo "   DELETE $BASE_URL/items/{id}"
echo "   POST $BASE_URL/posts (alias for /items)"
echo "   POST $BASE_URL/swipes"
echo "   GET  $BASE_URL/matches"
echo "   GET  $BASE_URL/matches/{id}"
echo "   GET  $BASE_URL/messages/{match_id}"
echo "   POST $BASE_URL/messages"
echo "   POST $BASE_URL/report"
echo "   POST $BASE_URL/block"
